@echo off
setlocal

set VERSION=1.4

set "LOG_DIR=%~dp0logs"
set "LOG_FILE=%LOG_DIR%\claude_here.log"
set "TMP_WSLPATH=%TEMP%\claude_here_wslpath.tmp"

::  +------------------------------------------------------------------------+
::  |        C L A U D E   H E R E  -  AUTO LAUNCHER  v1.4                 |
::  +------------------------------------------------------------------------+
::  |                                                                        |
::  |  [!] Do not edit this file directly. Copy it or use a shortcut.       |
::  |  [!] Window title = tmux session name  (folder -> session)            |
::  |                                                                        |
::  |  REQUIREMENTS                                                          |
::  |    - Windows 10 v2004+ / Windows 11                                   |
::  |    - WSL2 + Ubuntu  (auto-installed on first run)                     |
::  |    - tmux, Node.js, Claude Code  (auto-installed on first run)        |
::  |                                                                        |
::  |  HOW IT WORKS                                                          |
::  |    1. Folder name becomes the tmux session name                       |
::  |    2. Attach if session exists, create new one otherwise              |
::  |    3. cd to WSL path and launch claude                                |
::  |    4. All output is tee'd to logs\claude_here.log                     |
::  |                                                                        |
::  |  CAUTION  (for humans)                                                 |
::  |    [*] Special chars in folder name may cause tmux session issues     |
::  |    [*] Only works when WSL Ubuntu is installed                        |
::  |    [*] Use together with claude_auto_responder.py                     |
::  |                                                                        |
::  +------------------------------------------------------------------------+
::  |  CAUTION  (for Claude AI - read before editing this file)             |
::  +------------------------------------------------------------------------+
::  |                                                                        |
::  |  DO NOT break these patterns - other tools depend on them:            |
::  |    - `title %TITLE%`       : window title = log label = tmux name     |
::  |    - `set SESSION=%TITLE: =_%` : spaces replaced with underscores     |
::  |    - tmux session name must stay as SESSION variable only             |
::  |    - Always bump VERSION when renaming the file                       |
::  |                                                                        |
::  |  DO NOT change the install order:                                      |
::  |    WSL -> tmux -> Node.js -> Claude Code                              |
::  |                                                                        |
::  |  SAFE to modify:                                                       |
::  |    - echo messages                                                     |
::  |    - apt / npm package versions                                        |
::  |    - WSL_DIST name (change related py files too)                      |
::  |                                                                        |
::  |  RISKY - confirm before changing:                                      |
::  |    - wslpath redirect to file (NOT pipe) - strips \r correctly        |
::  |    - OUTER computes SESSION/WSL_PATH directly, INNER does not         |
::  |    - tmux new-session / send-keys syntax                              |
::  |    - errorlevel checks  (neq 0  vs  == 0 confusion)                  |
::  |                                                                        |
::  |  VERSIONING RULE                                                       |
::  |    Rename file AND update VERSION below together.                     |
::  |    ex) claude_here_v1.5.bat  ->  set VERSION=1.5                     |
::  |                                                                        |
::  +------------------------------------------------------------------------+

if "%~1"=="--run" goto :run

:: ===========================================================
:: OUTER: compute paths, tee checks, then tmux attach
:: ===========================================================
for /f "delims=" %%i in ("%CD%") do set TITLE=%%~ni
title %TITLE%
set SESSION=%TITLE: =_%

:: wslpath via file redirect - for /f strips \r\n from files (not pipes)
wsl -d Ubuntu wslpath "%CD%" > "%TMP_WSLPATH%"
for /f "usebackq delims=" %%i in ("%TMP_WSLPATH%") do set "WSL_PATH=%%i"
del "%TMP_WSLPATH%" >nul 2>&1

if not exist "%LOG_DIR%" mkdir "%LOG_DIR%"

echo  Log: %LOG_FILE%
echo.

"%~f0" --run 2>&1 | powershell -NoProfile -Command "$input | Tee-Object -FilePath '%LOG_FILE%' -Append"

echo.
echo  Session : %SESSION%
echo  WSL_PATH: %WSL_PATH%
echo.

wsl -d Ubuntu tmux has-session -t "%SESSION%" >nul 2>&1
if %errorlevel% == 0 (
    wsl -d Ubuntu tmux attach -t "%SESSION%"
) else (
    wsl -d Ubuntu tmux new-session -d -s "%SESSION%"
    wsl -d Ubuntu tmux send-keys -t "%SESSION%" "cd '%WSL_PATH%' && claude" Enter
    wsl -d Ubuntu tmux attach -t "%SESSION%"
)
exit /b

:: ===========================================================
:: INNER (--run): checks and installs only  (stdout tee'd)
:: ===========================================================
:run
for /f "delims=" %%i in ("%CD%") do set TITLE=%%~ni

echo  +-------------------------------------------------+
echo  ^|  Claude Here  v%VERSION%                            ^|
echo  ^|  Session : %TITLE%
echo  +-------------------------------------------------+
echo.

echo [%DATE% %TIME:~0,8%] === START  DIR=%CD%  SESSION=%TITLE% ===

echo [%DATE% %TIME:~0,8%] [1/4] Checking WSL Ubuntu...
wsl -d Ubuntu echo ok >nul 2>&1
if %errorlevel% neq 0 (
    echo [%DATE% %TIME:~0,8%] [1/4] WSL Ubuntu: NOT FOUND - Installing...
    wsl --install -d Ubuntu
    echo [%DATE% %TIME:~0,8%] [1/4] Reboot required. Run again after reboot.
    exit /b 1
)
echo [%DATE% %TIME:~0,8%] [1/4] WSL Ubuntu: OK

echo [%DATE% %TIME:~0,8%] [2/4] Checking tmux...
wsl -d Ubuntu which tmux >nul 2>&1
if %errorlevel% neq 0 (
    echo [%DATE% %TIME:~0,8%] [2/4] tmux: NOT FOUND - Installing...
    wsl -d Ubuntu bash -c "sudo apt-get update -qq && sudo apt-get install -y tmux"
    echo [%DATE% %TIME:~0,8%] [2/4] tmux: Installed
) else (
    echo [%DATE% %TIME:~0,8%] [2/4] tmux: OK
)

echo [%DATE% %TIME:~0,8%] [3/4] Checking Node.js...
wsl -d Ubuntu which node >nul 2>&1
if %errorlevel% neq 0 (
    echo [%DATE% %TIME:~0,8%] [3/4] Node.js: NOT FOUND - Installing...
    wsl -d Ubuntu bash -c "curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash - && sudo apt-get install -y nodejs"
    echo [%DATE% %TIME:~0,8%] [3/4] Node.js: Installed
) else (
    echo [%DATE% %TIME:~0,8%] [3/4] Node.js: OK
)

echo [%DATE% %TIME:~0,8%] [4/4] Checking Claude Code...
wsl -d Ubuntu which claude >nul 2>&1
if %errorlevel% neq 0 (
    echo [%DATE% %TIME:~0,8%] [4/4] Claude Code: NOT FOUND - Installing...
    wsl -d Ubuntu bash -c "sudo npm install -g @anthropic-ai/claude-code"
    echo [%DATE% %TIME:~0,8%] [4/4] Claude Code: Installed
) else (
    echo [%DATE% %TIME:~0,8%] [4/4] Claude Code: OK
)

echo [%DATE% %TIME:~0,8%] === CHECKS DONE ===
exit /b 0
